apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: redis
    helm:
      values: |
        auth:
          enabled: false

    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 20.1.4
  syncPolicy:
    automated: {}
